name: gts_learn
description: GTS app for learning a sign language.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.1

dependencies:
  flutter:
    sdk: flutter

  # General
  auto_route: ^5.0.1
  freezed: ^2.1.0+1
  freezed_annotation: ^2.1.0
  camera: ^0.10.0+3
  flutter_hooks: ^0.18.5+1
  video_player: ^2.4.7
  device_info_plus: ^7.0.0


  # BLoC
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1

  # Dep. Injection
  injectable: ^1.5.3
  get_it: ^7.2.0

  # UI
  carousel_slider:
   git:
     url: https://github.com/BenPrzychodzki/flutter_carousel_slider
     ref: master
  google_fonts: ^3.0.1
  easy_rich_text: ^1.1.0
  flutter_native_splash: ^2.2.12

  # ML
  tflite_flutter:
    git:
      url: https://github.com/BenPrzychodzki/tflite_flutter_plugin.git
      ref: master
  tflite_flutter_helper:
    git:
      url: https://github.com/BenPrzychodzki/tflite_flutter_helper.git
      ref: master

  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  # Generators
  injectable_generator: ^1.5.4
  auto_route_generator: ^5.0.2
  build_runner: ^2.2.1

  # Testing
  bloc_test: ^9.1.0
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.2

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/gestures/
    - assets/images/
    - assets/images/2.0x/
    - assets/images/3.0x/

  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/icons/ui_icons.ttf
