name: gts_learn
description: GTS app for learning a sign language.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.1

dependencies:
  flutter:
    sdk: flutter

  # General
  auto_route: ^5.0.1
  freezed: ^2.1.0+1
  freezed_annotation: ^2.1.0

  # BLoC
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1

  # Dep. Injection
  injectable: ^1.5.3
  get_it: ^7.2.0

  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Generators
  injectable_generator: ^1.5.4
  auto_route_generator: ^5.0.2
  build_runner: ^2.2.1

  # Testing
  bloc_test: ^9.1.0
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.2

flutter:
  uses-material-design: true
  generate: true
